#%RAML 1.0 DataType
type: object
properties:
  valid: string
  number: integer
  local_format: integer
  international_format: integer
  country_prefix: integer
  country_code: string
  country_name: string
  location: string
  carrier: string
  line_type: string
