#%RAML 1.0 NamedExample

 
  {
    "valid" : "true",
    "number" : 15713420490,
    "local_format" : 5713420490,
    "international_format" : 15713420490,
    "country_prefix" : +1,
    "country_code" : "US",
    "country_name" : "United States of America",
    "location" : "Herndon",
    "carrier" : "Cellco Partnership (Verizon Wireless)",
    "line_type" : "mobile"
}